# Generated by Django 4.2.30 on 2026-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_delivery_type_order_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
