# Generated by Django 4.2.30 on 2026-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_qr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
