# Generated by Django 4.2.30 on 2026-07-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartitem_options_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
