# Generated by Django 4.2.30 on 2026-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_address_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
