# Generated by Django 4.2.30 on 2026-07-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationsystem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
