# Generated by Django 4.2.30 on 2026-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
