# Generated by Django 4.2.30 on 2026-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('reservation_confirmed', 'Reservation Confirmed'), ('new_order_pending', 'New Order Pending'), ('low_inventory', 'Low Inventory'), ('new_review', 'New Review')], max_length=50),
        ),
    ]
