from django.urls import path
from .views import auth_views, home_views, menu_views, cart_views, order_views, reservation_views, profile_views, review_views, payment_views

urlpatterns = [
    path("", home_views.home, name="home"),
    path("register/", auth_views.register, name="register"),
    path("login/", auth_views.login_view, name="login"),
    path("logout/", auth_views.logout_view, name="logout"),
    path("menu", menu_views.menu_list, name='menu'),
    path("menu/<int:item_id>/", menu_views.menu_detail, name="menu_detail"),
    path("cart/", cart_views.view_cart, name="view_cart"),
    path("cart/add/<int:item_id>/", cart_views.add_to_cart, name="add_to_cart"),
    path("cart/add-checkout/<int:item_id>/", cart_views.add_to_cart_and_checkout, name="add_to_cart_and_checkout"),
    path("cart/update/<int:item_id>/", cart_views.update_cart_item, name="update_cart_item"),
    path("cart/remove/<int:item_id>/", cart_views.remove_from_cart, name="remove_from_cart"),
    path("checkout/", order_views.checkout, name="checkout"),
    path("checkout/place/", order_views.place_order, name="place_order"),
    path("orders/<int:order_id>/", order_views.order_detail, name="order_detail"),
    path("orders/", order_views.order_history, name="order_history"),
    path("reservations/", reservation_views.my_reservations, name="my_reservations"),
    path("reservations/new/", reservation_views.make_reservation, name="make_reservation"),
    path("reservations/<int:reservation_id>/edit/", reservation_views.edit_reservation, name="edit_reservation"),
    path("reservations/<int:reservation_id>/cancel/", reservation_views.cancel_reservation, name="cancel_reservation"),
    path("profile/", profile_views.profile, name="profile"),
    path("profile/edit/", profile_views.edit_profile, name="edit_profile"),
    path("profile/change-password/", profile_views.change_password, name="change_password"),
    path("reviews/", review_views.my_reviews, name="my_reviews"),
    path("reviews/add/<int:menu_id>/", review_views.add_review, name="add_review"),
    path("reviews/<int:review_id>/edit/", review_views.edit_review, name="edit_review"),
    path("reviews/<int:review_id>/delete/", review_views.delete_review, name="delete_review"),
    path("payment-methods/", payment_views.payment_methods, name="payment_methods"),
    path("payment-methods/add/", payment_views.add_payment_method, name="add_payment_method"),
    path("payment-methods/<int:method_id>/delete/", payment_views.delete_payment_method, name="delete_payment_method"),
    path("payment-methods/<int:method_id>/default/", payment_views.set_default_payment_method, name="set_default_payment_method"),
]